version = 0.1

[default.deploy.parameters]
stack_name = "dig-job-server-qa"
s3_bucket = "dig-sam-artifacts-bucket"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=qa"
